[package]
name = "ext-metadata"
version = "0.1.0"
edition.workspace = true

[dependencies]
bencode = { path = "../bencode" }
peer-wire = { path = "../peer-wire" }
thiserror.workspace = true
sha1.workspace = true
tokio = { workspace = true, features = ["net", "io-util", "time"] }

[dev-dependencies]
bencode = { path = "../bencode" }
sha1.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }

[lints]
workspace = true
