[package]
name = "cli"
version = "0.1.0"
edition.workspace = true

[dependencies]
metainfo = { path = "../metainfo" }
tracker = { path = "../tracker" }
engine = { path = "../engine" }
anyhow = "1"
tokio = { workspace = true, features = ["full"] }
tracing-subscriber = "0.3"

[dev-dependencies]
peer-wire = { path = "../peer-wire" }
hex.workspace = true
sha2 = "0.10"
tempfile = "3"
tokio = { workspace = true, features = ["full"] }

[lints]
workspace = true
