[package]
name = "engine"
version = "0.1.0"
edition.workspace = true

[dependencies]
metainfo = { path = "../metainfo" }
tracker = { path = "../tracker" }
peer-wire = { path = "../peer-wire" }
dht = { path = "../dht" }
ext-metadata = { path = "../ext-metadata" }
ext-pex = { path = "../ext-pex" }
nat = { path = "../nat" }
thiserror.workspace = true
sha1.workspace = true
fastrand.workspace = true
tracing = "0.1"
tokio = { workspace = true, features = ["net", "io-util", "time", "sync", "macros", "rt"] }

[dev-dependencies]
bencode = { path = "../bencode" }
tempfile = "3"
tokio = { workspace = true, features = ["rt-multi-thread"] }
tracing-subscriber = "0.3"

[lints]
workspace = true
